import Head from 'next/head'

import { Container } from 'react-bootstrap'

import Footer from "components/common/Footer"
import CustomModal from 'components/common/Modal'
import Header from 'components/common/Header'

export default function Layout({ children }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <Container fluid>
          {children}
        </Container>
      </main>
      <Footer />
      <CustomModal></CustomModal>
    </>
  )
}
