import Head from 'next/head'
import styles from 'styles/Home.module.css'

import Button from 'react-bootstrap/Button'

import Footer from 'components/common/footer'
import CustomModal from 'components/common/modal'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Button variant="primary">Open Modal</Button>
      </main>

      <Footer></Footer>
    </div>
  )
}
